"""init alembic

Revision ID: 1ee3a6aebd1d
Revises: 
Create Date: 2023-10-11 20:10:36.123774

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ee3a6aebd1d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_account", sa.Column("id", sa.String(length=30), nullable=False), sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "venue_managers",
        sa.Column("id", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "venues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("street", sa.String(length=30), nullable=False),
        sa.Column("city", sa.String(length=30), nullable=False),
        sa.Column("zip_code", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("phone", sa.Integer(), nullable=False),
        sa.Column("website", sa.String(length=30), nullable=True),
        sa.Column("image_link", sa.String(length=30), nullable=True),
        sa.Column("genres", sa.String(length=30), nullable=True),
        sa.Column("manager_id", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["venue_managers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("venues")
    op.drop_table("venue_managers")
    op.drop_table("user_account")
    # ### end Alembic commands ###
