"""add genre to band

Revision ID: 4d0225614456
Revises: 658655aa93c5
Create Date: 2023-12-13 16:44:09.658581

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d0225614456"
down_revision: Union[str, None] = "658655aa93c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bands", sa.Column("genres", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bands", "genres")
    # ### end Alembic commands ###
