"""add band manager

Revision ID: 62e3a0e70766
Revises: 
Create Date: 2023-12-18 19:09:13.799152

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62e3a0e70766"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_account", sa.Column("id", sa.String(length=30), nullable=False), sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "bands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("city", sa.String(length=30), nullable=True),
        sa.Column("zip_code", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=30), nullable=True),
        sa.Column("website_link", sa.String(length=120), nullable=True),
        sa.Column("image_link", sa.String(), nullable=True),
        sa.Column("genres", sa.String(length=120), nullable=True),
        sa.Column("manager_id", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "venues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("street", sa.String(length=30), nullable=False),
        sa.Column("city", sa.String(length=30), nullable=False),
        sa.Column("zip_code", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("phone", sa.Integer(), nullable=False),
        sa.Column("website", sa.String(length=30), nullable=True),
        sa.Column("image_link", sa.String(), nullable=True),
        sa.Column("genres", sa.String(length=30), nullable=True),
        sa.Column("manager_id", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("venues")
    op.drop_table("bands")
    op.drop_table("user_account")
    # ### end Alembic commands ###
