"""model user under main app

Revision ID: 7486fdbf7149
Revises:
Create Date: 2023-10-04 17:59:57.369309

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7486fdbf7149"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_account", sa.Column("id", sa.String(length=30), nullable=False), sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "venues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("address", sa.String(length=30), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("zip_code", sa.Integer(), nullable=False),
        sa.Column("phone", sa.Integer(), nullable=False),
        sa.Column("website", sa.String(length=30), nullable=True),
        sa.Column("image_link", sa.String(length=30), nullable=True),
        sa.Column("genres", sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("venues")
    op.drop_table("user_account")
    # ### end Alembic commands ###
