"""add venue model

Revision ID: 7caf26a60bde
Revises: 57a8e0f3dc7b
Create Date: 2023-09-29 18:35:56.569314

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7caf26a60bde"
down_revision: Union[str, None] = "57a8e0f3dc7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "venues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("address", sa.String(length=30), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("zip_code", sa.Integer(), nullable=False),
        sa.Column("phone", sa.Integer(), nullable=False),
        sa.Column("website", sa.String(length=30), nullable=False),
        sa.Column("image_link", sa.String(length=30), nullable=False),
        sa.Column("genres", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("venues")
    # ### end Alembic commands ###
