"""add about venue

Revision ID: a840e84e705b
Revises: 62e3a0e70766
Create Date: 2023-12-18 19:40:00.300990

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a840e84e705b"
down_revision: Union[str, None] = "62e3a0e70766"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("venues", sa.Column("about", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("venues", "about")
    # ### end Alembic commands ###
