"""add city field

Revision ID: bc2604359d30
Revises: 7486fdbf7149
Create Date: 2023-10-10 09:53:36.201086

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc2604359d30"
down_revision: Union[str, None] = "7486fdbf7149"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("venues", sa.Column("street", sa.String(length=30), nullable=False))
    op.add_column("venues", sa.Column("city", sa.String(length=30), nullable=False))
    op.drop_column("venues", "address")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("venues", sa.Column("address", sa.VARCHAR(length=30), nullable=False))
    op.drop_column("venues", "city")
    op.drop_column("venues", "street")
    # ### end Alembic commands ###
